-- Esquema para el sistema de chat en tiempo real de Maidex
-- Este archivo debe ejecutarse en la consola SQL de Supabase

-- Tabla de mensajes
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  is_user BOOLEAN NOT NULL DEFAULT FALSE,
  user_id TEXT,
  conversation_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  action TEXT,
  drive_files JSONB,
  file_id TEXT
);

-- Índices para mejorar el rendimiento de consultas
CREATE INDEX IF NOT EXISTS messages_conversation_id_idx ON messages (conversation_id);
CREATE INDEX IF NOT EXISTS messages_created_at_idx ON messages (created_at);
CREATE INDEX IF NOT EXISTS messages_user_id_idx ON messages (user_id);

-- Política de seguridad basada en Row Level Security (RLS)
-- Habilitar RLS en la tabla
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Política para permitir lectura de mensajes
CREATE POLICY "Usuarios pueden leer sus propios mensajes" 
  ON messages 
  FOR SELECT 
  USING (auth.uid()::text = user_id);

-- Política para permitir inserción de mensajes
CREATE POLICY "Usuarios pueden insertar sus propios mensajes" 
  ON messages 
  FOR INSERT 
  WITH CHECK (auth.uid()::text = user_id);

-- Política para permitir actualización de mensajes
CREATE POLICY "Usuarios pueden actualizar sus propios mensajes" 
  ON messages 
  FOR UPDATE 
  USING (auth.uid()::text = user_id);

-- Habilitar Realtime para la tabla de mensajes
-- Nota: La habilitación de Realtime se hace a través de la interfaz de Supabase
-- Database > Replication > Realtime > Tables > messages 